name: Deploy to Dev, Staging, and Main

# This workflow now triggers ONLY on a push to these three branches.
# Merging a pull request also counts as a push to the base branch.
on:
  push:
    branches:
      - dev
      - staging
      - main

jobs:
  # =================================================================
  # ==                DEPLOY TO DEVELOPMENT                        ==
  # =================================================================
  deploy-dev:
    # This job will only run if the push was to the 'dev' branch.
    if: github.ref == 'refs/heads/dev'
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push backend image
        uses: docker/build-push-action@v5
        with:
          context: ./backend
          file: ./backend/Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository }}/backend:dev

      - name: Build and push frontend image
        uses: docker/build-push-action@v5
        with:
          context: ./frontend
          file: ./frontend/Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository }}/frontend:dev

      - name: Deploy to server via SSH
        run: |
          mkdir -p ~/.ssh/
          echo "${{ secrets.DEV_SSH_KEY }}" > ~/.ssh/deploy_key
          chmod 600 ~/.ssh/deploy_key
          ssh-keyscan -H "${{ secrets.DEV_SSH_HOST }}" >> ~/.ssh/known_hosts
          ssh -T -i ~/.ssh/deploy_key ${{ secrets.DEV_SSH_USERNAME }}@${{ secrets.DEV_SSH_HOST }} << 'EOF'
            set -e
            cd /opt/aaf/dev
            git pull origin dev
            echo "${{ secrets.DEV_ENV_FILE }}" > .env
            
            # Stop and remove old containers before starting new ones
            docker-compose -f docker-compose.yml down
            
            docker-compose -f docker-compose.yml pull
            docker-compose -f docker-compose.yml up -d --build
            echo "Deployment to dev successful!"
          EOF

  # =================================================================
  # ==                DEPLOY TO STAGING                            ==
  # =================================================================
  deploy-staging:
    # This job will only run if the push was to the 'staging' branch.
    if: github.ref == 'refs/heads/staging'
    runs-on: ubuntu-latest
    environment: staging
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push backend image
        uses: docker/build-push-action@v5
        with:
          context: ./backend
          file: ./backend/Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository }}/backend:staging

      - name: Build and push frontend image
        uses: docker/build-push-action@v5
        with:
          context: ./frontend
          file: ./frontend/Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository }}/frontend:staging

      - name: Deploy to server via SSH
        run: |
          mkdir -p ~/.ssh/
          echo "${{ secrets.STAGING_SSH_KEY }}" > ~/.ssh/deploy_key
          chmod 600 ~/.ssh/deploy_key
          ssh-keyscan -H "${{ secrets.STAGING_SSH_HOST }}" >> ~/.ssh/known_hosts
          ssh -T -i ~/.ssh/deploy_key ${{ secrets.STAGING_SSH_USERNAME }}@${{ secrets.STAGING_SSH_HOST }} << 'EOF'
            set -e
            cd /opt/aaf/staging
            git pull origin staging
            echo "${{ secrets.STAGING_ENV_FILE }}" > .env

            # Stop and remove old containers before starting new ones
            docker-compose -f docker-compose.yml down

            docker-compose -f docker-compose.yml pull
            docker-compose -f docker-compose.yml up -d --build
            echo "Deployment to staging successful!"
          EOF

  # =================================================================
  # ==                DEPLOY TO MAIN (PRODUCTION)                  ==
  # =================================================================
  deploy-main:
    # This job will only run if the push was to the 'main' branch.
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    environment: main
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push backend image
        uses: docker/build-push-action@v5
        with:
          context: ./backend
          file: ./backend/Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository }}/backend:main

      - name: Build and push frontend image
        uses: docker/build-push-action@v5
        with:
          context: ./frontend
          file: ./frontend/Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository }}/frontend:main

      - name: Deploy to server via SSH
        run: |
          mkdir -p ~/.ssh/
          echo "${{ secrets.MAIN_SSH_KEY }}" > ~/.ssh/deploy_key
          chmod 600 ~/.ssh/deploy_key
          ssh-keyscan -H "${{ secrets.MAIN_SSH_HOST }}" >> ~/.ssh/known_hosts
          ssh -T -i ~/.ssh/deploy_key ${{ secrets.MAIN_SSH_USERNAME }}@${{ secrets.MAIN_SSH_HOST }} << 'EOF'
            set -e
            cd /opt/aaf/main
            git pull origin main
            echo "${{ secrets.MAIN_ENV_FILE }}" > .env

            # Stop and remove old containers before starting new ones
            docker-compose -f docker-compose.yml down

            docker-compose -f docker-compose.yml pull
            docker-compose -f docker-compose.yml up -d --build
            echo "Deployment to main successful!"
          EOF